HW13_Django/project_quotes/hw10_quotes/hw10_quotes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('super_quotes.urls')),
    path('users/', include('users.urls')),
]

HW13_Django/project_quotes/hw10_quotes/super_quotes/urls.py
from django.urls import path

from . import views

app_name = "super_quotes"

urlpatterns = [
    path('', views.home, name='home'),
    path('<int:page>', views.home, name='root_paginate'),
    path('author/<int:_id>', views.author_about, name='author_about'),
    path('add_quote/', views.add_quote, name='add_quote'),
    path('add_author/', views.add_author, name='add_author'),
    path('add_tag/', views.add_tag, name='add_tag'),
    path('tag/<int:_id>/', views.find_tag, name='find_tag'),
    path('tag/<str:_id>/', views.find_tag, name='find_tag'),
    path('search_quotes/', views.search_quotes, name='search_quotes'),
    path('parse_quotes/', views.parse_quotes, name='parse_quotes'),

]

HW13_Django/project_quotes/hw10_quotes/users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView
from .views import RegisterView, ResetPasswordView
from .forms import LoginForm

app_name = "users"

urlpatterns = [
    path('signup/', RegisterView.as_view(), name='register'),
    path('signin/', LoginView.as_view(
        template_name="users/signin.html",
        authentication_form=LoginForm,
        redirect_authenticated_user=True
    ), name='login'),
    path('logout/', LogoutView.as_view(
        template_name="users/logout.html",
    ), name='logout'),
    path('reset-password/', ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

HW13_Django/project_quotes/hw10_quotes/super_quotes/models.py
from django.db import models


# Create your models here.
class Author(models.Model):
    fullname = models.CharField(max_length=50)
    date_born = models.CharField(max_length=50)
    born_location = models.CharField(max_length=150)
    bio = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.fullname


class Tag(models.Model):
    name = models.CharField(max_length=40, null=False, unique=True)

    def __str__(self):
        return self.name


class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.quote

HW13_Django/project_quotes/hw10_quotes/super_quotes/forms.py
from django.forms import ModelForm, CharField, TextInput, DateField, SelectMultiple, \
    ModelChoiceField, Select, ModelMultipleChoiceField
from .models import Author, Quote, Tag


class AuthorForm(ModelForm):
    fullname = CharField(max_length=50, required=True, widget=TextInput(attrs={"class": "form-control"}))
    date_born = DateField(widget=TextInput(attrs={"class": "form-control"}))
    born_location = CharField(max_length=200, required=True, widget=TextInput(attrs={"class": "form-control"}))
    bio = CharField(required=True, widget=TextInput(attrs={"class": "form-control"}))

    class Meta:
        model = Author
        fields = ['fullname', 'date_born', 'born_location', 'bio']


class QuoteForm(ModelForm):
    quote = CharField(required=True, widget=TextInput(attrs={"class": "form-control"}))
    tags = ModelMultipleChoiceField(queryset=Tag.objects.all().order_by('name'),
                                    widget=SelectMultiple(attrs={'class': 'form_control', 'size': 10}))
    author = ModelChoiceField(queryset=Author.objects.all().order_by('fullname'),
                              widget=Select(attrs={"class": "form-select"}))

    class Meta:
        model = Quote
        fields = ['author', 'tags', 'quote']


class TagForm(ModelForm):
    name = CharField(max_length=50, required=True, widget=TextInput(attrs={"class": "form-control"}))

    class Meta:
        model = Tag
        fields = ['name']

HW13_Django/project_quotes/hw10_quotes/super_quotes/views.py
import datetime
import re

import requests
from bs4 import BeautifulSoup
from django.core.paginator import Paginator
from django.db.models import Count, Q
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from .models import Quote, Author, Tag

from .forms import AuthorForm, QuoteForm, TagForm


def home(request, page=1):
    quotes = Quote.objects.all()
    per_page = 5
    paginator = Paginator(list(quotes), per_page)
    quotes_on_page = paginator.page(page)
    top_tags = Quote.objects.values('tags__name').annotate(quote_count=Count('tags__name')).order_by('-quote_count')[
               :10]
    war_info = war_spider()
    return render(request, "super_quotes/index.html", context={"quotes": quotes_on_page, 'top_tags': top_tags,
                                                               'war_info': war_info})


def author_about(request, _id):
    author = Author.objects.get(pk=_id)
    return render(request, 'super_quotes/author.html', context={'author': author})


@login_required
def add_quote(request):
    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            new_quote = form.save()
            return redirect(to='super_quotes:home')
        else:
            return render(request, 'super_quotes/add_quote.html',
                          context={'form': QuoteForm, 'message': "Форма невірна"})
    return render(request, 'super_quotes/add_quote.html', context={'form': QuoteForm()})


@login_required
def add_author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            new_author = form.save()
            return redirect(to='super_quotes:home')
        else:
            return render(request, 'super_quotes/add_author.html',
                          context={'form': AuthorForm, 'message': "Форма невірна"})
    return render(request, 'super_quotes/add_author.html', context={'form': AuthorForm()})


@login_required
def add_tag(request):
    if request.method == 'POST':
        form = TagForm(request.POST)
        if form.is_valid():
            new_tag = form.save()
            return redirect(to='super_quotes:home')
        else:
            return render(request, 'super_quotes/add_tag.html',
                          context={'form': TagForm, 'message': "Форма невірна"})
    return render(request, 'super_quotes/add_tag.html', context={'form': TagForm})


def find_tag(request, _id):
    per_page = 5
    if isinstance(_id, int):
        quotes = Quote.objects.filter(tags=_id).all()
    elif isinstance(_id, str):
        tag_id = Tag.objects.filter(name=_id).first()
        quotes = Quote.objects.filter(tags=tag_id).all()
    paginator = Paginator(list(quotes), per_page)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    top_tags = Quote.objects.values('tags__id', 'tags__name').annotate(quote_count=Count('tags__name')).order_by(
        '-quote_count')[:10]

    return render(request, 'super_quotes/find_tag.html',
                  context={'quotes': page_obj, 'tag_name': _id, 'top_tags': top_tags})


def search_quotes(request):
    query = request.GET.get('q')
    quotes = Quote.objects.filter(
        Q(tags__name__icontains=query) |
        Q(quote__icontains=query) |
        Q(author__fullname__icontains=query)
    ).distinct()

    return render(request, 'super_quotes/search_quotes.html', context={'quotes': quotes, 'query': query})


def parse_quotes(request):
    base_url = 'http://quotes.toscrape.com'

    def get_author_urls():
        author_links = []
        response = requests.get(base_url)
        soup = BeautifulSoup(response.text, 'html.parser')
        quotes = soup.find_all('div', class_='quote')
        for q in quotes:
            author_links.append(q.find("a", href=True).get('href'))
        return author_links

    def quote_spider():
        created_quotes = []
        response = requests.get(base_url)
        soup = BeautifulSoup(response.text, 'html.parser')
        content = soup.select('div[class=col-md-8] div[class=quote]')
        for el in content:
            quote_text = el.find('span', attrs={'class': 'text'}).text
            author_fullname = el.find('small', attrs={'class': 'author'}).text
            author, created = Author.objects.get_or_create(fullname=author_fullname)

            tags = (list(filter(bool, [t.text.strip() for t in el.find('div', class_='tags').find_all('a')])))

            new_quote, created = Quote.objects.get_or_create(quote=quote_text, author=author)
            if created:
                for tag_name in tags:
                    tag, _ = Tag.objects.get_or_create(name=tag_name)
                    new_quote.tags.add(tag)
            new_quote.save()
            created_quotes.append(new_quote)
        return created_quotes

    def author_spider():
        author_links = get_author_urls()
        created_authors = []
        for link in author_links:
            response = requests.get(base_url + link)
            soup = BeautifulSoup(response.text, 'lxml')
            content = soup.select('div[class=container] div[class=author-details]')
            for el in content:
                fullname = el.find('h3', attrs={'class': 'author-title'}).text.strip()
                date_born = el.find('span', attrs={'class': 'author-born-date'}).text.strip()
                born_location = el.find('span', attrs={'class': 'author-born-location'}).text.strip()
                bio = el.find('div', attrs={'class': 'author-description'}).text.strip()
                author, created = Author.objects.get_or_create(fullname=fullname, date_born=date_born,
                                                               born_location=born_location,
                                                               bio=bio)
                author.save()
                created_authors.append(author)
        return created_authors

    def parsing():
        return author_spider(), quote_spider()

    return render(request, 'super_quotes/parse_quotes.html', context={'final_parse': parsing,
                                                                      'base_url': base_url})


def war_spider():
    base_url = 'https://index.minfin.com.ua/ua/russian-invading/casualties'
    response = requests.get(base_url)
    soup = BeautifulSoup(response.text, 'html.parser')
    content = soup.find_all('div', class_='casualties')
    numbers = re.findall(r'\d+(?=\s*<small>\(\+\d+\)</small></li>|</li>)', str(content[0]))

    war_dict = {
        'date': datetime.date.today().strftime("%d.%m.%Y"),
        'tanks': int(numbers[0]),
        'bbm': int(numbers[1]),
        'artillery': int(numbers[2]),
        'rszw': int(numbers[3]),
        'ppo': int(numbers[4]),
        'planes': int(numbers[5]),
        'helicopters': int(numbers[6]),
        'drones': int(numbers[7]),
        'rockets': int(numbers[8]),
        'ships': int(numbers[9]),
        'vehicles': int(numbers[10]),
        'auto': int(numbers[11]),
        'orks': int(re.findall(r'Особовий склад\s*—\s*близько\s*(\d+)\s*<span', str(content[0]))[0])
    }
    return war_dict

HW13_Django/project_quotes/hw10_quotes/super_quotes/templates/super_quotes/add_author.html
{%extends "super_quotes/base.html"%}

{% block content %}
<h3>Додати атвора</h3>

{%if form.errors %}
<span class="alert alert-danger" role="alert">{{form.non_field_errors}}</span>
{% endif %}

<form method="post">
    {% csrf_token %}
    <div class="row mb-3 col-md-6">
        <label>Автор</label>
        {{form.fullname}}
    </div>
    <div class="row mb-3 col-md-6">
        <label class="form-label">Дата народження</label>
        {{form.date_born}}
    </div>
    <div class="row mb-3 col-md-6">
        <label>Місце народження</label>
        {{form.born_location}}
    </div>
      <div class="row mb-3 col-md-6">
        <label>Біографія</label>
        {{form.bio}}
    </div>


    <button type="submit" class="btn btn-primary">Додати автора</button>
</form>
{% endblock %}

HW13_Django/project_quotes/hw10_quotes/super_quotes/templates/super_quotes/add_quote.html
{%extends "super_quotes/base.html"%}

{% block content %}
<h3>Додати цитату</h3>

{%if form.errors %}
<span class="alert alert-danger" role="alert">{{form.non_field_errors}}</span>
{% endif %}

<form method="post">
    {% csrf_token %}
    <div class="row mb-3 col-md-6">
        <label>Цитата</label>
        {{form.quote}}
    </div>
    <div class="row mb-3 col-md-6">
        <label class="form-label">Теги (обери один або декілька)</label>
        {{form.tags}}
    </div>
    <div class="row mb-3 col-md-6">
        <label>Автор</label>
        {{form.author}}
    </div>
    <button type="submit" class="btn btn-primary">Додати цитату</button>
</form>
{% endblock %}

HW13_Django/project_quotes/hw10_quotes/super_quotes/templates/super_quotes/add_tag.html
{%extends "super_quotes/base.html"%}

{% block content %}
<h3>Додати тег</h3>

{%if form.errors %}
<span class="alert alert-danger" role="alert">{{form.non_field_errors}}</span>
{% endif %}

<form method="post">
    {% csrf_token %}
    <div class="row mb-3 col-md-6">
        <label>Тег</label>
        {{form.name}}
    </div>
    <button type="submit" class="btn btn-primary">Додати тег</button>
</form>

{% endblock %}

HW13_Django/project_quotes/hw10_quotes/super_quotes/templates/super_quotes/author.html
{%extends "super_quotes/base.html"%}
{% load extract %}


{% block content %}
<div class="author-details">
    <h3 class="author-title">{{author.fullname}}</h3>
        <p><strong>Born:</strong> <span class="author-born-date">{{author.date_born}}</span> <span
                class="author-born-location">{{author.born_location}}</span></p>
        <p><strong>Description:</strong></p>
        <div class="author-description">{{author.bio}}</div>
</div>

{% endblock %}

HW13_Django/project_quotes/hw10_quotes/super_quotes/templates/super_quotes/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css"
          integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">

    {% load static %}
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'super_quotes/img/img.png'%}">
    <link rel="stylesheet" href="{% static 'super_quotes/style.css' %}">

    <title>{{ title }}</title>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-primary mb-3">
    <div class="container-fluid">
        <a class="navbar-brand" href="/" style="font-size: 1.5rem">Super Quotes</a>

        <form class="d-flex ms-auto" role="search" method="get" action="{% url 'super_quotes:search_quotes' %}">
        <input class=" form-control me-2
        " type="search" name="q" placeholder="Пошук" aria-label="Search">
        <button class="btn btn-light" type="submit">Знайти</button>
        </form>

        {% if user.is_authenticated %}
        <p class="mb-0 ps-3">Ласкаво просимо, {{user.username}} ❤️❤️❤️</p>
        <div class="d-flex justify-content-between align-items-center">
            <a class="btn btn-info me-2" href="{% url 'super_quotes:add_quote' %}">Додати цитату</a>
            <a class="btn btn-info me-2" href="{% url 'super_quotes:add_author' %}">Додати автора</a>
            <a class="btn btn-info me-2" href="{% url 'super_quotes:add_tag' %}">Додати тег</a>

        </div>
        {% else %}
        <div class="d-flex justify-content-between align-items-center">
            <a class="btn btn-success me-2" href="{% url 'users:register' %}">Зареєструватись</a>
            <a class="btn btn-success" href="{% url 'users:login' %}">Ввійти</a>
        </div>
        {% endif %}
        {% if request.user.is_superuser %}
        <div class="d-flex justify-content-between align-items-center">
            <a class="btn btn-dark me-2" href="{% url 'super_quotes:parse_quotes' %}">Парсити цитати</a>
        </div>
        {% endif %}
        {% if user.is_authenticated %}
        <a class="btn btn-info" href="{% url 'users:logout' %}">Вийти</a>
        {% endif %}
    </div>

</nav>

<div class="container mb-5">
    {% block content %}

    {% endblock %}
</div>

<footer class="bg-light text-center py-3 fixed-bottom">
    <p>© 2023 Super Quotes by <a class="mb-0" href="https://github.com/DenBilokon/PyWEB_HW10">Denis Bilokon</a></p>
</footer>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-r6IvZ35Kj41FWP63M0uJw4Ov7xW0E8Y9/lbmcS5SdWeKjPpI8irTWVgJ4mfwvmyV"
        crossorigin="anonymous"></script>

</body>
</html>

HW13_Django/project_quotes/hw10_quotes/super_quotes/templates/super_quotes/find_tag.html
{%extends "super_quotes/base.html"%}
{% load extract %}

{% block content %}
<div class="row">
    <div class="col-md-8">
        {% for quote in quotes %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">{{quote.quote}}</span>
            <span>by <small class="author" itemprop="author">{{quote.author.fullname}}</small>
            <a href="{% url 'super_quotes:author_about' quote.author.id %}">(about)</a>
            </span>
            <div class="tags">
                Tags:
                {% for tag in quote.tags.all %}
                <a class="tag" href="{% url 'super_quotes:find_tag' tag.id %}">{{tag.name}}</a>
                {% endfor %}
            </div>
        </div>
        {% endfor %}
        <nav>
            <ul class="pagination">
                <li class="previous">
                    {% if quotes.has_previous %}
                    <a href="?page=1" class="btn btn-light">&laquo; Перша</a>
                    <a href="?page={{ quotes.previous_page_number }}" class="btn btn-light">Попередня</a>
                    {% endif %}
                    <span class="current">Сторінка {{ quotes.number }} з {{ quotes.paginator.num_pages }}</span>
                    {% if quotes.has_next %}
                    <a href="?page={{ quotes.next_page_number }}" class="btn btn-light">Наступна</a>
                    <a href="?page={{ quotes.paginator.num_pages }}" class="btn btn-light">Остання &raquo;</a>
                    {% endif %}
                </li>
            </ul>
        </nav>
    </div>
    <div class="col-md-4 themed-grid-col">
        <h2>Top 10 Tags</h2>
        {% for tag in top_tags %}
        <div class="tags">
            <a class="btn btn-info" href="{% url 'super_quotes:find_tag' tag.tags__name %}">{{tag.tags__name}}</a>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

HW13_Django/project_quotes/hw10_quotes/super_quotes/templates/super_quotes/index.html
{%extends "super_quotes/base.html"%}
{% load extract %}


{% block content %}
<div class="row">
    <div class="col-md-8 themed-grid-col">
        {% for quote in quotes %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">{{quote.quote}}</span>
            <span>by <small class="author" itemprop="author">{{quote.author.fullname}}</small>
        <a href="{% url 'super_quotes:author_about' quote.author.id %}">(about)</a>
        </span>
            <div class="tags">
                Tags:
                {% for tag in quote.tags.all %}
                <a class="tag" href="{% url 'super_quotes:find_tag' tag.id %}">{{tag.name}}</a>
                {% endfor %}
            </div>
        </div>
        {% endfor %}
        <nav>
            <ul class="pagination">
                <li class="previous">
                    {% if quotes.has_previous %}
                    <a href="/1" class="btn btn-light">&laquo; Перша</a>
                    <a href="/{{ quotes.previous_page_number }}" class="btn btn-light">Попередня</a>
                    {% endif %}
                    <span class="current">Сторінка {{ quotes.number }} з {{ quotes.paginator.num_pages }}</span>
                    {% if quotes.has_next %}
                    <a href="/{{ quotes.next_page_number }}" class="btn btn-light">Наступна</a>
                    <a href="/{{ quotes.paginator.num_pages }}" class="btn btn-light">Остання &raquo;</a>
                    {% endif %}
            </ul>
        </nav>

    </div>
    <div class="col-md-2 themed-grid-col">
        <h4>Top 10 Tags</h4>
        {% for tag in top_tags %}
        <div class="tags">
            <p class="btn btn-info" href="{% url 'super_quotes:find_tag' tag.tags__name %}">{{tag.tags__name}}</p>
        </div>
        {% endfor %}
    </div>
    <div class="col-md-2">
        <h4>Чудова статистика</h4>
        <p class="btn btn-warning">На дату: {{ war_info.date }}</p>
        <p class="btn btn-info">Танки: {{ war_info.tanks }}</p>
        <p class="btn btn-info">ББМ: {{ war_info.bbm }}</p>
        <p class="btn btn-info">Гармати: {{ war_info.artillery }}</p>
        <p class="btn btn-info">РСЗВ: {{ war_info.rszw }}</p>
        <p class="btn btn-info">Засоби ППО: {{ war_info.ppo }}</p>
        <p class="btn btn-info">Літаки: {{ war_info.planes }}</p>
        <p class="btn btn-info">Гелікоптери: {{ war_info.helicopters }}</p>
        <p class="btn btn-info">БПЛА: {{ war_info.drones }}</p>
        <p class="btn btn-info">Крилаті ракети: {{ war_info.rockets }}</p>
        <p class="btn btn-info">Кораблі (катери): {{ war_info.ships }}</p>
        <p class="btn btn-info">Автомобілі: {{ war_info.vehicles }}</p>
        <p class="btn btn-info">Спец. техніка: {{ war_info.auto }}</p>
        <p class="btn btn-info">Орки: {{ war_info.orks }}</p>
    </div>

</div>
{% endblock %}

HW13_Django/project_quotes/hw10_quotes/super_quotes/templates/super_quotes/parse_quotes.html
{% extends "super_quotes/base.html" %}

{% block content %}
<div class="row">
    <h4>Завершено парсинг сайту {{ base_url }}</h4>
    <div class="col-md-8">
        {% for author in final_parse.author_spider %}
        {% if author_created %}

        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">Новий автор "{{ author }}" був доданий до бази даних!</span>
            {% endif %}
            {% endfor %}
        </div>
        {% for quote in final_parse.quote_spider %}
        {% if quote_created %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">Нова цитата "{{ quote }}" була додана до бази даних!</span>
            {% endif %}
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

HW13_Django/project_quotes/hw10_quotes/super_quotes/templates/super_quotes/search_quotes.html
{%extends "super_quotes/base.html"%}
{% load extract %}

{% block content %}
<div class="row">
    <h4>Пошук за словом: {{query}}</h4>
    <div class="col-md-8">
        {% for quote in quotes %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">{{quote.quote}}</span>
            <span>by <small class="author" itemprop="author">{{quote.author.fullname}}</small>
            <a href="{% url 'super_quotes:author_about' quote.author.id %}">(about)</a>
            </span>
            <div class="tags">
                Tags:
                {% for tag in quote.tags.all %}
                <a class="tag" href="{% url 'super_quotes:find_tag' tag.id %}">{{tag.name}}</a>
                {% endfor %}
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="col-md-4 themed-grid-col">
        <h2>Top 10 Tags</h2>
        {% for tag in top_tags %}
        <div class="tags">
            <a class="btn btn-info" href="{% url 'super_quotes:find_tag' tag.tags__name %}">{{tag.tags__name}}</a>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

HW13_Django/project_quotes/hw10_quotes/super_quotes/templates/super_quotes/test.html
<div class="col-md-2">
            <h4>Чудова статистика</h4>
            <p class="btn btn-warning">На дату: {{ war_info.date }}</p>
            <p class="btn btn-info">Танки: {{ war_info.tanks }}</p>
            <p class="btn btn-info">ББМ: {{ war_info.bbm }}</p>
            <p class="btn btn-info">Гармати: {{ war_info.artillery }}</p>
            <p class="btn btn-info">РСЗВ: {{ war_info.rszw }}</p>
            <p class="btn btn-info">Засоби ППО: {{ war_info.ppo }}</p>
            <p class="btn btn-info">Літаки: {{ war_info.planes }}</p>
            <p class="btn btn-info">Гелікоптери: {{ war_info.helicopters }}</p>
            <p class="btn btn-info">БПЛА: {{ war_info.drones }}</p>
            <p class="btn btn-info">Крилаті ракети: {{ war_info.rockets }}</p>
            <p class="btn btn-info">Кораблі (катери): {{ war_info.ships }}</p>
            <p class="btn btn-info">Автомобілі: {{ war_info.vehicles }}</p>
            <p class="btn btn-info">Спец. техніка: {{ war_info.auto }}</p>
            <p class="btn btn-info">Орки: {{ war_info.orks }}</p>
        </div>