HW13_Django/project_quotes/hw10_quotes/hw10_quotes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('super_quotes.urls')),
    path('users/', include('users.urls')),
]

HW13_Django/project_quotes/hw10_quotes/users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView
from .views import RegisterView, ResetPasswordView
from .forms import LoginForm

app_name = "users"

urlpatterns = [
    path('signup/', RegisterView.as_view(), name='register'),
    path('signin/', LoginView.as_view(
        template_name="users/signin.html",
        authentication_form=LoginForm,
        redirect_authenticated_user=True
    ), name='login'),
    path('logout/', LogoutView.as_view(
        template_name="users/logout.html",
    ), name='logout'),
    path('reset-password/', ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

HW13_Django/project_quotes/hw10_quotes/users/models.py
from django.db import models

# Create your models here.

HW13_Django/project_quotes/hw10_quotes/users/forms.py
from django.forms import CharField, TextInput, EmailField, EmailInput, PasswordInput
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


class RegisterForm(UserCreationForm):
    username = CharField(max_length=100, required=True, widget=TextInput(attrs={"class": "form-control"}))
    first_name = CharField(max_length=100, widget=TextInput(attrs={"class": "form-control"}))
    last_name = CharField(max_length=100, widget=TextInput(attrs={"class": "form-control"}))
    email = EmailField(max_length=100, required=True, widget=EmailInput(attrs={"class": "form-control"}))
    password1 = CharField(min_length=6, max_length=12, required=True,
                          widget=PasswordInput(attrs={"class": "form-control"}))
    password2 = CharField(min_length=6, max_length=12, required=True,
                          widget=PasswordInput(attrs={"class": "form-control"}))

    class Meta:
        model = User
        fields = ("username", "first_name", "last_name", "email", "password1", "password2")


class LoginForm(AuthenticationForm):
    username = CharField(max_length=100, required=True, widget=TextInput(attrs={"class": "form-control"}))
    password = CharField(min_length=6, max_length=12, required=True,
                         widget=PasswordInput(attrs={"class": "form-control"}))

    class Meta:
        model = User
        fields = ("username", "first_name", "last_name", "email", "password1", "password2")

HW13_Django/project_quotes/hw10_quotes/users/views.py
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View
from django.contrib import messages


from .forms import RegisterForm


class RegisterView(View):
    form_class = RegisterForm
    template_name = "users/signup.html"

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            redirect(to="/")
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        return render(request, self.template_name, {"form": self.form_class})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data["username"]
            messages.success(request, f"Вітаємо, {username}, акаунт успішно створено!")
            return redirect(to="/users/signin/")

        return render(request, self.template_name, {"form": form})


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'users/password_reset.html'
    email_template_name = 'users/password_reset_email.html'
    html_email_template_name = 'users/password_reset_email.html'
    success_url = reverse_lazy('users:password_reset_done')
    success_message = "An email with instructions to reset your password has been sent to %(email)s."
    subject_template_name = 'users/password_reset_subject.txt'

HW13_Django/project_quotes/hw10_quotes/users/templates/users/logout.html
{% extends "super_quotes/base.html" %}
{% block content %}

<div class="h3">Ви успішно вийшли. До нових зустрічей!</div>


<div class="col-md-4">
            <p>
                <a class="btn btn-info" href="/">Повернутись на головну сторінку</a>
            </p>
        </div>
{% endblock %}

HW13_Django/project_quotes/hw10_quotes/users/templates/users/password_reset.html
{% extends "super_quotes/base.html" %}

{% block content %}

<h2>Password reset</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Request password reset</button>
</form>

{% endblock %}

HW13_Django/project_quotes/hw10_quotes/users/templates/users/password_reset_complete.html
{% extends "super_quotes/base.html" %}

{% block content %}

    <h2>Password reset complete!</h2>

{% endblock %}

HW13_Django/project_quotes/hw10_quotes/users/templates/users/password_reset_confirm.html
{% extends "super_quotes/base.html" %}

{% block content %}

<h2>Enter new password</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save new password</button>
</form>

{% endblock %}

HW13_Django/project_quotes/hw10_quotes/users/templates/users/password_reset_done.html
{% extends "super_quotes/base.html" %}

{% block content %}

<h2>Password reset request sent</h2>
<p>We've emailed you with instructions on how to reset your password.</p>

{% endblock %}

HW13_Django/project_quotes/hw10_quotes/users/templates/users/password_reset_email.html
{% autoescape off %}
<body>
<p>Hi {{ user.username }},</p>
<p>You requested a password reset for your account. Please follow this link to set a new password:</p>
<p>
    <a href="{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}">
        Reset password
    </a>
</p>
<p>If you didn't request a password reset, please ignore this email.</p>
<p>Thanks,</p>
<p>The Our Team</p>
{% endautoescape %}

HW13_Django/project_quotes/hw10_quotes/users/templates/users/signin.html
{%extends "super_quotes/base.html"%}

{% block content %}
<h3>Ввійти</h3>

{%if form.errors %}
<span class="alert alert-danger" role="alert">{{form.non_field_errors}}</span>
{% endif %}

{%if messages %}
{%for msg in messages %}
<span class="alert {% if msg.tags %} alert-{{msg.tags}} {% endif %}" role="alert">{{msg}}</span>
{% endfor %}
{% endif %}


<form method="post">
    {% csrf_token %}
    <div class="row mb-3 col-md-6">
        <label for="{{form.username.id_for_label}}">Логін</label>
        {{form.username}}
        <span>{{form.errors.username}}</span>
    </div>
    <div class="row mb-3 col-md-6">
        <label for="{{form.password.id_for_label}}">Пароль:</label>
        {{form.password}}
        <span>{{form.errors.password}}</span>
    </div>
    <button type="submit" class="btn btn-info">Заново</button>
    <button type="submit" class="btn btn-primary">Ввійти</button>
    <div class="small text-center">
        <a href="{% url "users:password_reset" %}" class="text-center"><i>Forgot Password?</i></a>
    </div>
</form>
{% endblock %}

HW13_Django/project_quotes/hw10_quotes/users/templates/users/signup.html
{%extends "super_quotes/base.html"%}

{% block content %}
<h3>Реєстрація</h3>

{%if form.errors %}
<span class="alert alert-danger" role="alert">{{form.non_field_errors}}</span>
{% endif %}


<form method="post">
    {% csrf_token %}
    <div class="row mb-3 col-md-6">
        <label>Логін</label>
        {{form.username}}
        <span>{{form.errors.username}}</span>
    </div>
    <div class="row mb-3 col-md-6">
        <label>Прізвище</label>
        {{form.first_name}}
        <span>{{form.errors.first_name}}</span>
    </div>
    <div class="row mb-3 col-md-6">
        <label>Ім'я</label>
        {{form.last_name}}
        <span>{{form.errors.last_name}}</span>
    </div>
    <div class="row mb-3 col-md-6">
        <label>Ел. Пошта</label>
        {{form.email}}
        <span>{{form.errors.email}}</span>
    </div>
    <div class="row mb-3 col-md-6">
        <label>Пароль:</label>
        {{form.password1}}
        <span>{{form.errors.password1}}</span>
    </div>
    <div class="row mb-3 col-md-6">
        <label>Підтвердити пароль:</label>
        {{form.password2}}
        <span>{{form.errors.password2}}</span>
    </div>
    <button type="submit" class="btn btn-info">Заново</button>
    <button type="submit" class="btn btn-primary">Реєструємось</button>
</form>
{% endblock %}